function getId() {
    let urlParams = new URLSearchParams(window.location.search);
    let id = urlParams.get('id')
    return id;

}

let trainerData = [{
    //CK Start//
    id: 1,
    imgSrc: '../images/ck perfumes/male/1.jpeg',
    name: "IN2U",
    details: "Calvin Klein's fragrance captures a modern essence with a blend of fresh, floral, and woody notes. Uniquely contemporary, the CK perfume embodies simplicity and sophistication, creating an enduring and distinctive aroma.  .",
    price: " Price: 2,150.00 PKR"
},
{
    id: 2,
    imgSrc: '../images/ck perfumes/female/1.webp',
    name: "CALVIN BEAUTY",
    details: "CK Women's Perfume: A captivating symphony of floral and fruity notes, embracing femininity with grace. Elegantly modern, this fragrance is a celebration of confidence, style, and timeless allure for women",
    price: " Price: 2,300.00 PKR"

},
{
    id: 3,
    imgSrc: '../images/ck perfumes/unisex/1.jfif',
    name: "CK Adventure EDT",
    details: "CK Unisex Perfume embodies a dynamic fusion of fresh citrus and woody undertones, creating a versatile and invigorating scent. Modern and timeless, it complements individuality with a subtle yet captivating allure",
    price: " Price: 6,999.00 PKR",
},
{
    id: 4,
    imgSrc: '../images/ck perfumes/femail/Calvin-Klein-Eternity-Eau-De-Parfum-Perfume-for-Women-3-4-oz_c26dc82f-d866-40d4-87b7-9e0f4fa30cb4_1.b29107368b792fd1a5f6ce5387b08345.webp',
    name: "Eterity",
    details: "Calvin Klein's perfume exudes timeless elegance with a harmonious blend of floral, fruity, and woody notes. This iconic fragrance encapsulates a modern and sophisticated essence, making a subtle yet memorable statement",
    price: " Price: 1,250.00 PKR",
},
{
    id: 5,
    imgSrc: '../images/ck perfumes/female/2.webp',
    name: "ETERNITY KLEIN",
    details: "CK Women's Perfume: A harmonious blend of floral and oriental notes, exuding modern femininity. This fragrance captures the essence of sophistication, empowering women with a timeless and alluring charm",
    price: " Price: 7,800.00 PKR",
},
{
    id: 6,
    imgSrc: '../images/ck perfumes/unisex/common3.avif',
    name: "CK ONE COLOGNE",
    details: "CK Unisex Perfume is a captivating blend of citrus, floral, and woody notes, creating a versatile and sophisticated scent. Its modern allure appeals to individuals seeking a timeless and gender-neutral fragrance.",
    price: " Price: 12,600.00 PKR",
},
{
    id: 7,
    imgSrc: '../images/ck perfumes/male/3.jpeg',
    name: "CK WHITE COLOGNE",
    details: "Calvin Klein's fragrance is a captivating symphony of citrus, floral, and musky notes. This iconic perfume epitomizes contemporary chic, offering a fresh and invigorating scent that lingers with understated sophistication.",
    price: " Price: 12,000.00 PKR",
},
{
    id: 8,
    imgSrc: '../images/ck perfumes/female/3.jpg',
    name: "CK Sensual",
    details: "CK Women's Perfume: A captivating blend of floral and fruity notes, radiating modern elegance and confidence. This fragrance embodies the essence of femininity, leaving a lasting and enchanting impression.",
    price: " Price: 16,000.00 PKR",
},
{
    id: 9,
    imgSrc: '../images/ck perfumes/unisex/3.jfif',
    name: "GREY IN2U",
    details: "CK Unisex Perfume is a harmonious fusion of citrus, floral, and musky notes, creating a captivating and versatile fragrance. Its modern elegance appeals to individuals of all genders, offering a timeless allure.",
    price: " Price: 14,500.00 PKR",
},
{
    id: 10,
    imgSrc: '../images/ck perfumes/male/4.jpg',
    name: "CK Rosepacific",
    details: "Calvin Klein's perfume is a captivating fusion of floral and fruity notes, creating a modern and alluring scent. It embodies a timeless elegance that is both fresh and sophisticated, leaving a lasting impression. ",
    price: " Price: 8,000.00 PKR",
},
{
    id: 11,
    imgSrc: '../images/ck perfumes/female/4.jpeg',
    name: "ESCAPE",
    details: "CK Women's Perfume: A mesmerizing fusion of floral and fruity accords, creating an enchanting and sophisticated aura. This fragrance embodies modern femininity, leaving a trail of confidence and timeless allure",
    price: " Price: 15,000.00 PKR",
},
{
    id: 12,
    imgSrc: '../images/ck perfumes/unisex/common3.webp',
    name: "CK ONE",
    details: "CK Unisex Perfume exudes a harmonious blend of citrus, floral, and woody notes, creating a captivating and versatile fragrance suitable for all. Modern and timeless, it complements individuality with universal appeal",
    price: " Price: 7,800.00 PKR",
},
{
    id: 13,
    imgSrc: '../images/ck perfumes/male/5.jpg',
    name: "KLEIN MK1",
    details: "Calvin Klein's fragrance is a captivating fusion of floral and woody notes, embodying modern sophistication. With a timeless allure, it strikes a perfect balance between freshness and subtle sensuality.",
    price: " Price: 3,000.00 PKR",
},
{
    id: 14,
    imgSrc: '../images/ck perfumes/female/5.jpeg',
    name: "GOLDEN BEAUTY",
    details: "CK Women's Perfume: A sublime fusion of floral and fruity notes, radiating modern elegance and confidence. This fragrance captures the essence of femininity, leaving a lasting and enchanting impression.",
    price: " Price: 45,000.00 PKR",
},
{
    id: 15,
    imgSrc: '../images/ck perfumes/unisex/5.jfif',
    name: "ETERNITY INTENSE",
    details: "CK Unisex Perfume: A captivating fusion of citrus, floral, and woody notes, offering a versatile and modern fragrance. Its timeless allure suits individuals of any gender, creating a unique and sophisticated experience",
    price: " Price: Rs.5,999.00 PKR",
},
{
    id: 16,
    imgSrc: '../images/ck perfumes/male/6.webp',
    name: "OBSESSION",
    details: "Calvin Klein's perfume is a harmonious blend of citrus, floral, and woody notes, creating a modern, fresh, and sophisticated fragrance. It captures the essence of contemporary style with a lasting allure",
    price: " Price: 3,000.00 PKR",
},
{
    id: 17,
    imgSrc: '../images/ck perfumes/female/6.jpg',
    name: "CK RED ONE",
    details: "CK Brand Perfume for females is a captivating fragrance that combines floral and fruity notes, creating a timeless and elegant scent. It exudes confidence and sophistication, making every moment memorable.",
    price: " Price: 45,000.00 PKR",
},
{
    id: 18,
    imgSrc: '../images/ck perfumes/unisex/6.jpeg',
    name: "FREE ENERGY",
    details: "CK Unisex Perfume is a captivating blend of citrus, floral, and musk notes, creating a versatile and modern fragrance. Its of any gender, embodying sophistication and style",
    price: " Price: 5,999.00 PKR",
},
{
    id: 19,
    imgSrc: '../images/ck perfumes/male/7.jpeg',
    name: "ETERNITY",
    details: "CK Men's Perfume: A dynamic fusion of citrus, spices, and woody undertones. Unleash the bold and masculine allure. Confidently sophisticated, this fragrance embodies modernity and timeless charisma for men.",
    price: " Price: 3,000.00 PKR",
},
{
    id: 20,
    imgSrc: '../images/ck perfumes/female/8.jpg',
    name: "ETERNITY MOVEMENT",
    details: "CK's female perfume is a harmonious blend of floral and fruity notes, evoking a sense of modern elegance and timeless allure. Captivating and confident, it leaves a lasting impression of sophistication.",
    price: " Price: 45,000.00 PKR",
},
{
    id: 21,
    imgSrc: '../images/ck perfumes/unisex/7.webp',
    name: "SUMMER DAZE",
    details: "CK Unisex Perfume is a captivating blend of citrus, floral, and musk notes, creating a versatile and modern fragrance. Its of any gender, embodying sophistication and style.",
    price: " Price: 5,999.00 PKR",
},
//CK End//
//HogoBoss Start//
{
    id: 22,
    imgSrc: '../images/hugo boss perfumes/male/1.webp',
    name: "BOSS NO.1",
    details: "Hugo Boss for Men: A captivating blend of sophistication and masculinity. Timeless scents crafted with precision, embodying the modern man's confidence and style. Unleash your charisma with every spray",
    price: " Price: 2,150.00 PKR",
},
{
    id: 23,
    imgSrc: '../images/hugo boss perfumes/female/1.webp',
    name: "BOSS FEMME",
    details: "Hugo Boss for Women: Embrace timeless elegance and feminine allure. This exquisite fragrance harmonizes floral notes with subtle warmth, creating a captivating and sophisticated essence for the modern woman.",
    price: " Price: 2,300.00 PKR",
},
{
    id: 24,
    imgSrc: '../images/hugo boss perfumes/unisex/1.webp',
    name: "BOSS",
    details: "Hugo Boss unveils a unisex fragrance, seamlessly merging woody and citrus notes. A modern and versatile scent, it embodies sophistication and individuality, appealing to those who appreciate refined, gender-neutral elegance.    ",
    price: " Price: 6,999.00 PKR",
},
{
    id: 25,
    imgSrc: '../images/hugo boss perfumes/male/2.webp',
    name: "HUGO",
    details: "Hugo Boss for Men: A refined fragrance capturing the essence of modern masculinity. With notes of sophistication and confidence, it's an aromatic journey that complements the discerning man's distinct style.",
    price: " Price: 6,000.00 PKR",
},
{
    id: 26,
    imgSrc: '../images/hugo boss perfumes/female/2.webp',
    name: "HUGO DEEP RED",
    details: "Hugo Boss for Women: A captivating symphony of elegance and femininity. This fragrance marries floral grace with sensual warmth, embodying the sophisticated essence of the modern woman with enduring allure ",
    price: " Price: 7,800.00 PKR",
},
{
    id: 27,
    imgSrc: '../images/hugo boss perfumes/unisex/2.jfif',
    name: "HUGO BOSS..1",
    details: "Hugo Boss presents a captivating unisex fragrance, harmonizing fresh citrus and warm woody notes. This versatile scent embodies modern elegance, appealing to individuals who appreciate a sophisticated and distinctive essence.",
    price: " Price: 12,600.00 PKR",
},
{
    id: 28,
    imgSrc: '../images/hugo boss perfumes/male/3.webp',
    name: "BOSS NO.6",
    details: "Hugo Boss for Men: A distinctive fusion of timeless elegance and contemporary allure. This iconic fragrance captures the essence of modern masculinity with its sophisticated blend of notes, creating an unforgettable olfactory experience.",
    price: " Price: 12,000.00 PKR",


},
{
    id: 29,
    imgSrc: '../images/hugo boss perfumes/female/3.webp',
    name: "HUGO",
    details: "Hugo Boss presents a captivating fragrance for women, embodying elegance and sophistication. With floral and fruity notes, this perfume captures the essence of modern femininity, leaving a lasting impression.",
    price: " Price: 16,000.00 PKR",


},
{
    id: 30,
    imgSrc: '../images/hugo boss perfumes/unisex/3.jpg',
    name: "Black Current",
    details: "Hugo Boss introduces a timeless unisex fragrance, seamlessly blending citrus and woody undertones. This versatile scent embodies modern sophistication, offering a unique and captivating aroma that transcends gender boundaries..",
    price: " Price: 14,500.00 PKR",
},
{
    id: 31,
    imgSrc: '../images/hugo boss perfumes/male/4.webp',
    name: "BOSS BOTTLED NIGHT",
    details: "Hugo Boss for Men: An embodiment of timeless elegance and modern masculinity. This fragrance seamlessly blends sophistication with a confident aura, creating an irresistible essence for the discerning man",
    price: " Price: 8,000.00 PKR",
},
{
    id: 32,
    imgSrc: '../images/hugo boss perfumes/female/4.webp',
    name: "BOSS MA VIE",
    details: "Hugo Boss for Men: A captivating blend of       freshness and sophistication. This iconic fragrance exudes modern masculinity with notes of crisp apple, spicy cardamom, and warm woods, creating a timeless allure",
    price: " Price: 15,000.00 PKR",
},
{
    id: 33,
    imgSrc: '../images/hugo boss perfumes/unisex/4.jfif',
    name: "ELIXER BOTTLED",
    details: "Hugo Boss for Women: A fragrance that epitomizes modern femininity. Elegantly blending floral and fruity notes with a touch of sophistication, it leaves an unforgettable and alluring trail for the empowered woman",
    price: " Price: 7,800.00 PKR",
},
{
    id: 34,
    imgSrc: '../images/hugo boss perfumes/male/5.webp',
    name: "BOSS THE SCENT",
    details: "Hugo Boss for Men: A signature scent of refined masculinity. With a fusion of crisp freshness and enduring woods, it encapsulates confidence and sophistication for the modern, discerning gentleman",
    price: " Price: 3,000.00 PKR",
},
{
    id: 35,
    imgSrc: '../images/hugo boss perfumes/female/5.webp',
    name: "BOSS ORANGE",
    details: "Hugo Boss for Women: A captivating blend of sophistication and sensuality. This fragrance combines floral and fruity notes, creating a timeless and empowering aura that resonates with the modern, confident woman.",
    price: " Price: 45,000.00 PKR",
},
{
    id: 36,
    imgSrc: '../images/hugo boss perfumes/unisex/5.jfif',
    name: "BOSS THE SCENT",
    details: "Hugo Boss unveils a magnetic unisex fragrance, fusing vibrant citrus and warm woods. A modern olfactory masterpiece, it resonates with sophistication, embodying a universally appealing scent for those seeking timeless elegance.",
    price: " Price: 5,999.00 PKR",
},
{
    id: 37,
    imgSrc: '../images/hugo boss perfumes/male/6.webp',
    name: "HUGO JUST DIFFERENT",
    details: "Hugo Boss for Men: A signature scent of refined masculinity. With a fusion of crisp freshness and enduring woods, it encapsulates confidence and sophistication for the modern, discerning gentleman",
    price: " Price: 3,000.00 PKR",
},
{
    id: 38,
    imgSrc: '../images/hugo boss perfumes/female/6.webp',
    name: "BOSS THE SCENT",
    details: "Hugo Boss presents a captivating fragrance for women, embodying elegance and sophistication. With floral and fruity notes, this perfume captures the essence of modern femininity, leaving a lasting impression .",
    price: " Price: 45,000.00 PKR",
},
{
    id: 39,
    imgSrc: '../images/hugo boss perfumes/unisex/6.jfif',
    name: "BLUE BOTTLED BOSS",
    details: "Hugo Boss introduces a captivating unisex fragrance, harmonizing fresh citrus and warm, sensuous woods. This modern, sophisticated scent transcends gender, offering a versatile and alluring essence for individuals with discerning taste",
    price: " Price: 5,999.00 PKR",
},
{
    id: 40,
    imgSrc: '../images/hugo boss perfumes/male/7.webp',
    name: "DARK BLUE",
    details: "Hugo Boss for Men: An embodiment of timeless elegance and modern masculinity. This fragrance seamlessly blends sophistication with a confident aura, creating an irresistible essence for the discerning man.",
    price: " Price: 3,000.00 PKR",
},
{
    id: 41,
    imgSrc: '../images/hugo boss perfumes/female/7.webp',
    name: "BOSS THE SCENT ABSOLUTE",
    details: "Hugo Boss for Women: A captivating blend of sophistication and sensuality. This fragrance combines floral and fruity notes, creating a timeless and empowering aura that resonates with the modern, confident woman",
    price: " Price: 45,000.00 PKR",
},
{
    id: 42,
    imgSrc: '../images/hugo boss perfumes/unisex/7.avif',
    name: "HUGO THE SCENT MAGNETIC",
    details: "Hugo Boss unveils a magnetic unisex fragrance, fusing vibrant citrus and warm woods. A modern olfactory masterpiece, it resonates with sophistication, embodying a universally appealing scent for those seeking timeless elegance.",
    price: " Price: 5,999.00 PKR",
},
// HogoBoss End//
// Dior Start//
{
    id: 43,
    imgSrc: '../images/dior perfumes/male/1.webp',
    name: "DIOR HOMME INTENSE",
    details: " Dior presents a distinguished fragrance for men, blending masculine sophistication with timeless charm. This captivating scent combines citrus and woody notes, embodying modern elegance for the confident and refined gentleman",
    price: " Price: 2,150.00 PKR",
},
{
    id: 44,
    imgSrc: '../images/dior perfumes/female/1.webp',
    name: "DIOR ADDICT",
    details: "Dior's feminine fragrances captivate with timeless elegance and modern allure. A symphony of florals, fruits, and musk creates an enchanting scent that embodies sophistication and the essence of effortless glamour..        ",
    price: " Price: 2,300.00 PKR",
},
{
    id: 45,
    imgSrc: '../images/dior perfumes/UNISEX/CHRISRTIAN DIOR.jfif',
    name: "CHRISTIAN DIOR",
    details: "  Dior's unisex fragrances redefine luxury with a harmonious fusion of bold notes. A symphony of sophistication, each scent captures the essence of modern allure, creating an unforgettable sensory experience.    ",
    price: " Price: 6,999.00 PKR",
},
{
    id: 46,
    imgSrc: '../images/dior perfumes/male/2.webp',
    name: "DIOR HOMME",
    details: "   Dior's masculine fragrance epitomizes timeless elegance. Combining citrus and woody notes, it exudes sophistication and modernity, creating an aura of confidence and refinement for the discerning man.  ",
    price: " Price: 6,000.00 PKR",
},
{
    id: 47,
    imgSrc: '../images/dior perfumes/female/2.webp',
    name: "JADORE",
    details: " Dior's female fragrances embody timeless elegance with a captivating blend of florals and sophistication. Each scent is a luxurious celebration of femininity, leaving an enchanting trail of grace and allure.    ",
    price: " Price: 7,800.00 PKR",
},
{
    id: 48,
    imgSrc: '../images/dior perfumes/UNISEX/dioressence-.jpg',
    name: "DIORESSENCE",
    details: "  Dior's unisex fragrances epitomize modern sophistication, harmonizing bold and timeless notes. Each scent is a captivating journey, seamlessly blending masculine and feminine elements for an alluring and versatile olfactory experience.     ",
    price: " Price: 12,600.00 PKR",
},
{
    id: 49,
    imgSrc: '../images/dior perfumes/male/3.webp',
    name: " DIOR HOMME SPORT",
    details: " Dior's masculine fragrance exudes timeless elegance, merging citrus freshness with woody depth. A symbol of sophistication, this scent captures the essence of modern masculinity, leaving a lasting impression of refined charm.    ",
    price: " Price: 12,000.00 PKR",
},
{
    id: 50,
    imgSrc: '../images/dior perfumes/female/3.webp',
    name: " HUPONIC DIOR ",
    details: "  Dior's female fragrances embody luxury and allure. A harmonious fusion of florals and sophistication, each scent is a captivating ode to femininity, leaving an indelible trail of grace and glamour.    ",
    price: " Price: 16,000.00 PKR",
},
{
    id: 51,
    imgSrc: "../images/dior perfumes/UNISEX/DIORISIMME.jpg",
    name: " SPECIAL DIORESSENCE ",
    details: "Dior's unisex fragrances balance bold and subtle notes, creating a harmonious symphony of sophistication. Versatile and alluring, each scent is a modern expression of timeless elegance for every individual.    ",
    price: " Price: 14,500.00 PKR",
},
{
    id: 52,
    imgSrc: '../images/dior perfumes/male/4.webp',
    name: " SAUVAGE ",
    details: "Dior for Men is a timeless fragrance that fuses citrus vibrancy with woody depth. A symbol of masculine sophistication, it captures the essence of modern elegance, leaving a lasting impression of refinement.    ",
    price: " Price: 8,000.00 PKR",
},
{
    id: 53,
    imgSrc: '../images/dior perfumes/female/4.webp',
    name: " MISS DIOR CHERIE ",
    details: " Dior's female fragrances embody timeless elegance with a captivating blend of florals and sophistication. Each scent is a luxurious celebration of femininity, leaving an enchanting trail of grace and allure ",
    price: " Price: 15,000.00 PKR",
},
{
    id: 54,
    imgSrc: '../images/dior perfumes/UNISEX/DUNE.avif',
    name: " DUNE ",
    details: "   Dior's unisex fragrances epitomize modern sophistication, harmonizing bold and timeless notes. Each scent is a captivating journey, seamlessly blending masculine and feminine elements for an alluring and versatile olfactory experience.     ",
    price: " Price: 7,800.00 PKR",
},
{
    id: 55,
    imgSrc: '../images/dior perfumes/male/5.webp',
    name: " FARHENHEIT ",
    details: " Dior's masculine fragrance exudes timeless elegance, merging citrus freshness with woody depth. A symbol of sophistication, this scent captures the essence of modern masculinity, leaving a lasting impression of refined charm       ",
    price: " Price: 3,000.00 PKR",
},
{
    id: 56,
    imgSrc: '../images/dior perfumes/female/PURE POISON.webp',
    name: " PURE POISON",
    details: "Dior's women's fragrances weave tales of timeless sophistication. A symphony of florals and allure, each scent captures the essence of elegance, leaving an unforgettable trail of grace and femininity       ",
    price: " Price: 45,000.00 PKR",
},
{
    id: 57,
    imgSrc: '../images/dior perfumes/UNISEX/EAU FRAICHE.webp',
    name: " EAU FRAICHE",
    details: "  Dior's unisex fragrances blend bold and subtle notes, embodying a modern symphony of sophistication. Versatile and captivating, each scent is a timeless celebration of individuality and refined allure      ",
    price: " Price: 5,999.00 PKR",
},
{
    id: 58,
    imgSrc: '../images/dior perfumes/male/6.webp',
    name: " SAUVAGE ELIXER",
    details: "   Dior for Men is an embodiment of refined masculinity. The fragrance seamlessly blends citrus and woody notes, creating a timeless and sophisticated scent that reflects strength, confidence, and modern elegance  ",
    price: " Price: 3,000.00 PKR",
},
{
    id: 59,
    imgSrc: '../images/dior perfumes/female/6.webp',
    name: "FOVEVER AND EVER  ",
    details: "  Dior's feminine fragrances, a dance of sophistication and allure. With floral symphonies, they embody timeless elegance, leaving a captivating trail of grace that lingers, an essence of refined femininity.      ",
    price: " Price: 45,000.00 PKR",
},
{
    id: 60,
    imgSrc: '../images/dior perfumes/UNISEX/HIGH ENERGY.jpg',
    name: "HIGH ENERGY DIOR ",
    details: "  Dior's unisex fragrances harmonize bold and timeless notes, crafting a modern symphony of sophistication. Versatile and captivating, each scent is a celebration of individuality, leaving a trail of magnetic allure",
    price: " Price: 5,999.00 PKR",
},
{
    id: 61,
    imgSrc: '../images/dior perfumes/male/7.webp',
    name: "EAU SAUVAGE ",
    details: "Dior for Men presents a captivating fragrance that merges citrus freshness with warm woods. This sophisticated scent embodies modern masculinity, exuding confidence and charm for the discerning gentleman.    ",
    price: " Price: 3,000.00 PKR",
},
{
    id: 62,
    imgSrc: '../images/dior perfumes/female/7.webp',
    name: "JADOORE INFINISSIME ",
    details: "  Dior's female fragrances radiate timeless elegance. A harmonious blend of florals and sophistication, each scent is an enchanting expression of femininity, leaving a lingering trail of grace and allure      ",
    price: " Price: 45,000.00 PKR",
},
{
    id: 63,
    imgSrc: '../images/dior perfumes/UNISEX/SAUVAGE COLOGNE.webp',
    name: "SAUVAGE COLOGNE ",
    details: "   Dior's unisex fragrances redefine elegance, seamlessly blending bold and timeless notes. Each scent is a modern symphony, a versatile olfactory masterpiece that transcends gender, leaving a trail of sophisticated allure.       ",
    price: " Price: 5,999.00 PKR",
},
//Dior End//
//Davodoff Start//
{
    id: 64,
    imgSrc: '../images/davidoff perfumes/male/1.webp',
    name: "  COOL WATER ",
    details: "  DAVIDOFF for Men: A bold symphony of invigorating freshness and rugged masculinity. Crisp notes of citrus and herbs meld with deep woods, creating a timeless fragrance for the modern man.     ",
    price: " Price: 2,150.00 PKR",
},
{
    id: 65,
    imgSrc: '../images/davidoff perfumes/female/1.webp',
    name: "  COOL WATER",
    details: "  	DAVIDOFF for Women: A symphony of floral elegance, fruity radiance, and warm sensuality. This iconic fragrance captures the essence of feminine allure, evoking sophistication and timeless charm for every occasion.      ",
    price: " Price: 2,300.00 PKR",
},
{
    id: 66,
    imgSrc: '../images/davidoff perfumes/unisex/1.jfif',
    name: " AMBER BLIND  ",
    details: " DAVIDOFF Unisex Fragrance: A harmonious fusion of zesty citruses, delicate florals, and warm woods. Timeless and versatile, it transcends gender, leaving an enchanting trail of modern sophistication and allure.    ",
    price: " Price: 6,999.00 PKR",
},
{
    id: 67,
    imgSrc: '../images/davidoff perfumes/male/2.webp',
    name: " ZINO DAVIDOFF",
    details: "     DAVIDOFF for Men: A bold symphony of invigorating freshness and rugged masculinity. Crisp notes of citrus and herbs meld with deep woods, creating a timeless fragrance for the modern man.    ",
    price: " Price: 6,000.00 PKR",
},
{
    id: 68,
    imgSrc: '../images/davidoff perfumes/female/2.webp',
    name: " WATER WAVE ",
    details: "    DAVIDOFF for Women: A mesmerizing fusion of floral grace, fruity vibrancy, and subtle warmth. This iconic fragrance captures the essence of feminine allure, radiating sophistication and timeless charm.    ",
    price: " Price: 7,800.00 PKR",
},
{
    id: 69,
    imgSrc: '../images/davidoff perfumes/unisex/2.avif',
    name: " ADVENTURE BEAUTY",
    details: "     DAVIDOFF Unisex Fragrance: A captivating blend of fresh citruses, subtle florals, and earthy undertones. Timeless in its appeal, this versatile scent transcends gender, embodying modern elegance and universal allure.   ",
    price: " Price: 12,600.00 PKR",
},
{
    id: 70,
    imgSrc: '../images/davidoff perfumes/male/3.webp',
    name: "  HOT WATER",
    details: "  DAVIDOFF for Men: A captivating harmony of citrus zest, aromatic herbs, and deep woods. This timeless fragrance embodies masculine strength, sophistication, and modern allure for the confident man.    ",
    price: " Price: 12,000.00 PKR",
},
{
    id: 71,
    imgSrc: '../images/davidoff perfumes/female/3.webp',
    name: " COOL WATER SEAROSE",
    details: "   DAVIDOFF for Women: A graceful dance of vibrant florals, luscious fruits, and subtle warmth. This enchanting fragrance embodies feminine elegance, creating an unforgettable aura of sophistication and timeless allure.    ",
    price: " Price: 16,000.00 PKR",
},
{
    id: 72,
    imgSrc: '../images/davidoff perfumes/unisex/3.jpg',
    name: "Black Current ",
    details: "DAVIDOFF Unisex: A magnetic harmony of vibrant citruses, delicate florals, and warm woods. This timeless fragrance transcends gender, leaving an indelible trail of modern sophistication and universal allure..",
    price: " Price: 14,500.00 PKR",
},
{
    id: 73,
    imgSrc: '../images/davidoff perfumes/male/4.webp',
    name: " STREET FIGHTER ",
    details: "   DAVIDOFF for Men: A bold symphony of invigorating freshness and rugged masculinity. Crisp notes of citrus and herbs meld with deep woods, creating a timeless fragrance for the modern man.    ",
    price: " Price: 8,000.00 PKR",
},
{
    id: 74,
    imgSrc: '../images/davidoff perfumes/female/4.webp',
    name: " Davidoff Hot Water EDT",
    details: " DAVIDOFF for Women: A graceful dance of vibrant florals, luscious fruits, and subtle warmth. This enchanting fragrance embodies feminine elegance, creating an unforgettable aura of sophistication and timeless allure.       ",
    price: " Price: 15,000.00 PKR",
},
{
    id: 75,
    imgSrc: '../images/davidoff perfumes/unisex/4.jpg',
    name: " WOOD BLEND ",
    details: "    DAVIDOFF Unisex Fragrance: A captivating fusion of fresh citruses, elegant florals, and warm woods. Timeless and versatile, it transcends gender, evoking a modern allure that lingers in every encounter.   ",
    price: " Price: 7,800.00 PKR",
},
{
    id: 76,
    imgSrc: '../images/davidoff perfumes/male/5.webp',
    name: "ADVENTURE ",
    details: "    DAVIDOFF for Men: A captivating harmony of citrus zest, aromatic herbs, and deep woods. This timeless fragrance embodies masculine strength, sophistication, and modern allure for the confident man        ",
    price: "  3,000.00 PKR",
},
{
    id: 77,
    imgSrc: '../images/davidoff perfumes/female/5.webp',
    name: "DAVIDOFF RUN WILD ",
    details: "  DAVIDOFF for Women: A harmonious blend of floral grace, fruity radiance, and sensual warmth. This captivating fragrance epitomizes feminine allure, leaving an indelible trail of sophistication and timeless charm.    ",
    price: " Price: 45,000.00 PKR",
},
{
    id: 78,
    imgSrc: '../images/davidoff perfumes/unisex/5.webp',
    name: " WINTER SHADOW ",
    details: "   DAVIDOFF Unisex: A harmonious blend of invigorating citruses, delicate florals, and warm woods. Timelessly alluring, this fragrance transcends gender, creating an enchanting aura of modern sophistication and universal appeal.    ",
    price: " Price: 5,999.00 PKR",
},
{
    id: 79,
    imgSrc: '../images/davidoff perfumes/male/6.webp',
    name: " COOL WATER INTENSE ",
    details: "DAVIDOFF for Men: A bold symphony of invigorating freshness and rugged masculinity. Crisp notes of citrus and herbs meld with deep woods, creating a timeless fragrance for the modern man..",
    price: " Price: 3,000.00 PKR",
},
{
    id: 80,
    imgSrc: '../images/davidoff perfumes/female/6.webp',
    name: "DAVIDOFF RUN WILD ",
    details: "    DAVIDOFF for Women: An enchanting fusion of floral elegance, luscious fruits, and subtle warmth. This timeless fragrance captures the essence of feminine sophistication, radiating an irresistible charm that lingers.   ",
    price: " Price: 45,000.00 PKR",
},
{
    id: 81,
    imgSrc: '../images/davidoff perfumes/unisex/6.jfif',
    name: "CARRIBEAN WATER  ",
    details: "    DAVIDOFF Unisex: A captivating fusion of vibrant citruses, soft florals, and warm woods. Timeless and gender-neutral, this fragrance embodies modern sophistication and universal allure, leaving a lasting impression wherever it goes.    ",
    price: " Price: 5,999.00 PKR",
},
{
    id: 82,
    imgSrc: '../images/davidoff perfumes/male/7.webp',
    name: "DAVIDOFF RUN WILD  ",
    details: "     DAVIDOFF for Men: A magnetic blend of citrus vibrancy, aromatic herbs, and robust woods. This iconic fragrance exudes timeless masculinity, evoking confidence and charisma for the modern man   ",
    price: " Price: 3,000.00 PKR",
},
{
    id: 83,
    imgSrc: '../images/davidoff perfumes/female/7.webp',
    name: " COOL WINTER ",
    details: "DAVIDOFF for Women: A captivating symphony of floral notes, fruity allure, and sensual warmth. This timeless fragrance epitomizes feminine elegance, leaving an unforgettable trail of sophistication and charm.",
    price: " Price: 45,000.00 PKR",
},
{
    id: 84,
    imgSrc: '../images/davidoff perfumes/unisex/7.jpg',
    name: "BLACK FIX ",
    details: " DAVIDOFF Unisex: A magnetic harmony of vibrant citruses, delicate florals, and warm woods. This timeless fragrance transcends gender, leaving an indelible trail of modern sophistication and universal allure.    ",
    price: " Price: 5,999.00 PKR",
},
//Davidoff End//
//Gucci Start//
{
    id: 85,
    imgSrc: '../images/gucci perfumes/male/1.webp',
    name: " GUCCI GUILTY ",
    details: "   Gucci's men's fragrances embody sophistication and charm, seamlessly blending timeless elegance with a modern edge. Rich, aromatic notes unfold in a harmonious dance, leaving a lingering trail of confidence and allure. Each Gucci scent is a statement of luxury, a masterpiece crafted for the discerning gentleman     ",
    price: " Price: 2,150.00 PKR",
},
{
    id: 86,
    imgSrc: '../images/gucci perfumes/femail/1.webp',
    name: "GUCCI BLOOM ",
    details: "  Gucci's women's fragrances epitomize timeless elegance, weaving floral and oriental notes into a harmonious bouquet. Each scent is a luxurious expression of femininity, leaving a trail of confidence and allure. Gucci captures modern sophistication and enduring charm.    ",
    price: " Price: 2,300.00 PKR",
},
{
    id: 87,
    imgSrc: '../images/gucci perfumes/unisex/1.webp',
    name: "MEMORIE D'UNE ODEUR ",
    details: "    Gucci's unisex fragrances redefine versatility, blending notes that transcend gender boundaries. A harmonious fusion of sophistication and modernity creates a captivating scent for all. Gucci captures the essence of inclusive elegance, where every spray is a statement of individual style and allure.   ",
    price: " Price: 6,999.00 PKR",
},
{
    id: 88,
    imgSrc: '../images/gucci perfumes/male/2.webp',
    name: "GUILTY POUR HOME ",
    details: "  Gucci's men's fragrances exude refined masculinity, intertwining bold and sensual notes. A symphony of sophistication unfolds, capturing the essence of contemporary elegance. Each Gucci scent is a magnetic expression of individual style and undeniable allure     ",
    price: " Price: 6,000.00 PKR",
},
{
    id: 89,
    imgSrc: '../images/gucci perfumes/femail/2.webp',
    name: " GUILTY POUR FEME ",
    details: " Gucci's women's fragrances radiate timeless allure, marrying floral and sensual notes in a symphony of elegance. Each scent is a luxurious expression of femininity, leaving a captivating and confident trail. Gucci perfumes epitomize modern sophistication and enduring charm.",  
    price: ": 7,800.00 PKR",
},
{
    id: 90,
    imgSrc: '../images/gucci perfumes/unisex/2.webp',
    name: "INTENSE OUD ",
    details: "Gucci's unisex fragrances embody a harmonious blend of sophistication and contemporary allure. Versatile notes intertwine seamlessly, creating a captivating scent that transcends gender boundaries. Each Gucci fragrance is a statement of individuality, celebrating the beauty of inclusive elegance.    ",
    price: " Price: 12,600.00 PKR",
},
{
    id: 91,
    imgSrc: '../images/gucci perfumes/male/3.webp',
    name: "GUCCI (NEW)  ",
    details: "Gucci's men's fragrances epitomize modern masculinity, seamlessly blending luxury and charisma. Distinctive notes create a captivating aura of sophistication, leaving an indelible impression. Each Gucci scent is a refined statement, an olfactory masterpiece for the discerning gentleman.",
    price: " Price: 12,000.00 PKR",
},
{
    id: 92,
    imgSrc: '../images/gucci perfumes/femail/3.webp',
    name: "GUCCI BAMBOO ",
    details: " Gucci's women's fragrances embody refined femininity, intertwining floral and sensual notes with a touch of sophistication. Each scent is a poetic blend of elegance and allure, leaving an enchanting and lasting impression. Gucci perfumes capture the essence of modern grace and timeless charm.    ",
    price: " Price: 16,000.00 PKR",
},
{
    id: 93,
    imgSrc: '../images/gucci perfumes/unisex/3.webp',
    name: " GUILTY OUD ",
    details: " Gucci's unisex fragrances redefine allure, seamlessly merging sophisticated and modern notes. A captivating blend transcends gender, creating a versatile scent. Each spray is a statement of individuality, celebrating inclusive elegance with a distinctive and timeless charm     ",
    price: " Price: 14,500.00 PKR",
},
{
    id: 94,
    imgSrc: '../images/gucci perfumes/male/4.webp',
    name: "GUILTY ABSOLUTE ",
    details: "Gucci's men's fragrances redefine sophistication, merging timeless allure with contemporary flair. A harmonious blend of captivating notes crafts an aura of confident elegance. Each Gucci scent is a refined masterpiece, embodying the essence of refined masculinity and style..        ",
    price: " Price:  8,000.00 PKR",
},
{
    id: 95,
    imgSrc: '../images/gucci perfumes/femail/4.webp',
    name: " FLORA GORGEOUS ",
    details: "   Gucci's women's fragrances embody refined allure, blending floral and sensual notes in a harmonious composition. Each scent is a luxurious expression of femininity, leaving a captivating and confident impression. Gucci perfumes capture modern sophistication and timeless grace.    ",
    price: " Price: 15,000.00 PKR",
},
{
    id: 96,
    imgSrc: '../images/gucci perfumes/unisex/4.webp',
    name: " GUCCI OUD ",
    details: "   Gucci's unisex fragrances capture a versatile allure, fusing sophisticated and contemporary notes. The scent transcends gender boundaries, creating a captivating and inclusive experience. Each spray is a statement of individual style, celebrating the beauty of diverse elegance with a timeless, magnetic charm.    ",
    price: " Price: 7,800.00 PKR",
},
{
    id: 97,
    imgSrc: '../images/gucci perfumes/male/5.webp',
    name: " MEMORIE D'UNE ODEUR ",
    details: "  Gucci's men's fragrances exude sophistication and allure, fusing classic charm with modern sensuality. A symphony of distinctive notes creates a captivating and confident scent, making each Gucci fragrance a statement of refined masculinity and timeless style   ",
    price: " Price: 3,000.00 PKR",
},
{
    id: 98,
    imgSrc: '../images/gucci perfumes/femail/5.webp',
    name: "GUILTY BLACK ",
    details: "   Gucci's women's fragrances radiate timeless allure, marrying floral and sensual notes in a symphony of elegance. Each scent is a luxurious expression of femininity, leaving a captivating and confident trail. Gucci perfumes epitomize modern sophistication and enduring charm.   ",
    price: " Price: 45,000.00 PKR",
},
{
    id: 99,
    imgSrc: '../images/gucci perfumes/unisex/5.webp',
    name: "THE EYES OF THE TIGER   ",
    details: " Gucci's unisex fragrances embody a harmonious blend of sophistication and contemporary allure. Versatile notes intertwine seamlessly, creating a captivating scent that transcends gender boundaries. Each Gucci fragrance is a statement of individuality, celebrating the beauty of inclusive elegance.    ",
    price: " Price: 5,999.00 PKR",
},
{
    id: 100,
    imgSrc: '../images/gucci perfumes/male/6.webp',
    name: " INTENSE OUD  ",
    details: " Gucci's men's fragrances epitomize modern masculinity, seamlessly blending luxury and charisma. Distinctive notes create a captivating aura of sophistication, leaving an indelible impression. Each Gucci scent is a refined statement, an olfactory masterpiece for the discerning gentleman.      ",
    price: " Price: 3,000.00 PKR",
},
{
    id: 101,
    imgSrc: '../images/gucci perfumes/femail/6.webp',
    name: "GUILTY ABSOLUTE ",
    details: "Gucci's women's fragrances embody refined femininity, intertwining floral and sensual notes with a touch of sophistication. Each scent is a poetic blend of elegance and allure, leaving an enchanting and lasting impression. Gucci perfumes capture the essence of modern grace and timeless charm  ",
    price: " Price: 45,000.00 PKR",
},
{
    id: 102,
    imgSrc: '../images/gucci perfumes/unisex/6.webp',
    name: " TEARS OF IRIS ",
    details: " Gucci's unisex fragrances redefine allure, seamlessly merging sophisticated and modern notes. A captivating blend transcends gender, creating a versatile scent. Each spray is a statement of individuality, celebrating inclusive ",
    price: " Price: 5,999.00 PKR",
},
{
    id: 103,
    imgSrc: '../images/gucci perfumes/male/7.webp',
    name: " GUILTY LOVE EDITION ",
    details: "   Gucci's men's fragrances exude refined masculinity, intertwining bold and sensual notes. A symphony of sophistication unfolds, capturing the essence of contemporary elegance. Each Gucci scent is a magnetic expression of individual style and undeniable allure.    ",
    price: " Price: 3,000.00 PKR",
},
{
    id: 104,
    imgSrc: '../images/gucci perfumes/femail/7.webp',
    name: "Gaicicu ",
    details: "   Gucci's women's fragrances epitomize timeless elegance, blending floral and oriental notes in a harmonious symphony. Each scent is a luxurious expression of femininity, leaving a trail of confidence and allure. Gucci captures the essence of modern sophistication and grace.   ",
    price: " Price: 45,000.00 PKR",
},
// Gucci End//
// j. Start//
{
    id: 105,
    imgSrc: '../images/j. perfumes/male/edge_2__1 men.webp',
    name: " EDGE ",
    details: "   J. for men: A fusion of strength and refinement. Bold notes intertwine with sophistication, creating a magnetic scent that exudes confidence and allure, leaving a lasting impression of masculine charisma.   ",
    price: " Price: 2,150.00 PKR",
},
{
    id: 106,
    imgSrc: '../images/j. perfumes/femail/4_3_97.webp',
    name: " LILIANE POUR PERFUME  ",
    details: "   J. for women: A harmonious blend of femininity and allure. With captivating notes, each scent is an expression of confidence, leaving an indelible trail of grace and timeless allure.    ",
    price: " Price: 2,300.00 PKR",
},
{
    id: 107,
    imgSrc: '../images/j. perfumes/unisex/energy3.webp',
    name: " ENERGY ",
    details: " J. Unisex Fragrance: A mesmerizing fusion of citrus brightness, floral elegance, and warm sensuality. Embrace the gender-neutral allure that defines sophistication and leaves an unforgettable trail of modern refinement",
    price: " Price: 6,999.00 PKR",
},
{
    id: 108,
    imgSrc: '../images/j. perfumes/male/exclusive_intense_3_ men.webp',
    name: " EXCLUSIVE INTENSE  ",
    details: "   J. for men: A symphony of strength and sophistication. Bold notes harmonize to create an unforgettable scent, embodying confidence and timeless allure, leaving a powerful and masculine impression.     ",
    price: " Price: 6,000.00 PKR",
},
{
    id: 109,
    imgSrc: '../images/j. perfumes/femail/adnan_sid_ph_2__1.webp',
    name: " CLASSIQUE  ",
    details: "J. for women: A captivating blend of femininity and sophistication. Elegant notes intertwine, creating a scent that exudes confidence and allure, leaving an indelible mark of timeless grace and charm.    ",
    price: " Price: 7,800.00 PKR",
},
{
    id: 110,
    imgSrc: '../images/j. perfumes/unisex/focus1_2_.webp',
    name: " FOCUS ",
    details: " J. captivates with a harmonious blend of citrus, sensual florals, and warm woods, embodying a sophisticated allure for all. A unisex fragrance that transcends boundaries, leaving a lasting impression.    ",
    price: " Price: 12,600.00 PKR",
},
{
    id: 111,
    imgSrc: '../images/j. perfumes/male/great_summit_1_ men.webp',
    name: "GREAT SUMMIT ",
    details: "    J. for men: A captivating blend of strength and elegance. Bold notes intertwine with sophistication, crafting a scent that exudes confidence and allure, leaving an indelible mark of timeless masculinity.    ",
    price: " Price: 12,000.00 PKR",
},
{
    id: 112,
    imgSrc: '../images/j. perfumes/femail/azbah_2__1.webp',
    name: "AZBAH  ",
    details: "  J. for women: A symphony of femininity and allure. With elegant notes harmonizing seamlessly, each scent is a declaration of confidence, leaving an unforgettable trail of grace and timeless charm.    ",
    price: " Price: 16,000.00 PKR",
},
{
    id: 113,
    imgSrc: '../images/j. perfumes/unisex/orange1.webp',
    name: "ORANGE ",
    details: "   J. Unisex Fragrance: A captivating symphony of vibrant citruses, lush florals, and subtle musk. Timeless and versatile, it transcends gender boundaries, leaving an indelible impression of modern elegance.     ",
    price: " Price: 14,500.00 PKR",
},
{
    id: 114,
    imgSrc: '../images/j. perfumes/male/janan_platinum_2_ men.webp',
    name: "JANAN PLATINUM ",
    details: "     J. for men: A compelling synthesis of strength and sophistication. With bold notes harmonizing seamlessly, each scent is a declaration of masculine charisma, leaving an enduring trail of confidence and allure.  ",
    price: " Price: 8,000.00 PKR",
},
{
    id: 115,
    imgSrc: '../images/j. perfumes/femail/bella_pourfemme_4__1.webp',
    name: " BELLA POUR FEMME ",
    details: "   J. for women: A magnetic fusion of grace and sophistication. Elegant notes intertwine seamlessly, creating a scent that exudes confidence and allure, leaving an indelible mark of timeless femininity. ",
    price: " Price: 15,000.00 PKR",
},
{
    id: 116,
    imgSrc: '../images/j. perfumes/unisex/oud_1.webp',
    name: "OUD ",
    details: "     J. captivates with a harmonious blend of citrus, sensual florals, and warm woods, embodying a sophisticated allure for all. A unisex fragrance that transcends boundaries, leaving a lasting impression.    ",
    price: " 7,800.00 PKR",
},
{
    id: 117,
    imgSrc: '../images/j. perfumes/male/marjaan-02 men.webp',
    name: "MARJAAN ",
    details: "J. for men: A magnetic fusion of strength and sophistication. Bold notes intertwine, creating a scent that exudes confidence and timeless allure, leaving an indelible mark of masculine charisma.",
    price: " Price: 3,000.00 PKR",
},
{
    id: 118,
    imgSrc: '../images/j. perfumes/femail/boxnbottle-s women.webp',
    name: "BEAUTIFUL ",
    details: "     J. for women: A symphony of femininity and allure. With elegant notes harmonizing seamlessly, each scent is a declaration of confidence, leaving an unforgettable trail of grace and timeless charm.    ",
    price: " Price: 45,000.00 PKR",
},
{
    id: 119,
    imgSrc: '../images/j. perfumes/unisex/peace2.webp',
    name: "PEACE  ",
    details: "J. unisex: A captivating synthesis of strength and sophistication. Bold notes harmonize seamlessly, creating a scent that transcends gender, embodying confidence and timeless allure for a universally magnetic presence."
},
{
    id: 120,
    imgSrc: '../images/j. perfumes/male/ruler_1_ men.webp',
    name: "RULER ",
    details: "    J. for men: A charismatic blend of rugged masculinity and refined elegance. Each scent is a powerful statement, a symphony of bold notes creating an unforgettable aura of strength and allure.    ",
    price: " Price: 3,000.00 PKR",
},
{
    id: 121,
    imgSrc: '../images/j. perfumes/femail/komal_1__2.webp',
    name: "KOMAL ",
    details: "    J. for women: A captivating blend of femininity and allure. Elegant notes intertwine, creating a scent that exudes confidence and grace, leaving a lasting impression of timeless charm and sophistication.    ",
    price: " Price: 45,000.00 PKR",
},
{
    id: 122,
    imgSrc: '../images/j. perfumes/unisex/rose_water1.webp',
    name: "ROSE WATER  ",
    details: "    J. unisex: A harmonious fusion of strength and elegance. Bold notes intertwine with sophistication, creating a magnetic scent that transcends gender, leaving a lasting impression of confidence and allure   ",
    price: " Price: 5,999.00 PKR",
},
{
    id: 123,
    imgSrc: '../images/j. perfumes/male/sm1_5_ men.webp',
    name: "SM ALL ROUNDER ",
    details: " J. for men: A bold fusion of masculinity and sophistication. With captivating notes, each scent is a journey of confidence, leaving an indelible trail of strength and allure.    ",
    price: " Price: 3,000.00 PKR",
},
{
    id: 124,
    imgSrc: '../images/j. perfumes/femail/moscow_3_.webp',
    name: "MOSCOW POUR FEMME ",
    details: " J. for women: A harmonious blend of femininity and allure. With captivating notes, each scent is an expression of confidence, leaving an indelible trail of grace and timeless allure. ",
    price: " Price: 45,000.00 PKR",
},
{
    id: 125,
    imgSrc: '../images/j. perfumes/unisex/sleep3.webp',
    name: "SLEEP ",
    details: "  J. captivates with a harmonious blend of citrus, sensual florals, and warm woods, embodying a sophisticated allure for all. A unisex fragrance that transcends boundaries, leaving a lasting impression    ",
    price: " Price: 5,999.00 PKR",
},
//j. End//
{
    id: 126,
    imgSrc: './Educationimages/idcard.jpg',
    name: "ID card cover   ",
    details: " Introducing the Secure ID Card Cover—an essential accessory designed to protect and preserve your identification cards and badges during your educational tour. Crafted with durability, functionality, and professional aesthetics in mind, our ID card cover ensures your important credentials remain secure and presentable throughout your journey.        ",
    price: " Price:$15",
},
{
    id: 127,
    imgSrc: './Educationimages/istockphoto-1324847242-612x612.jpg',
    name: "Shoes    ",
    details: " Introducing Exploration-Ready Travel Shoes—an essential accessory designed to provide comfort, support, and style during your educational tour. Crafted with durability, versatility, and practicality in mind, our travel shoes ensure you can navigate new environments, engage in field studies, and explore diverse terrains with ease.        ",
    price: " Price:$30",
},
{
    id: 128,
    imgSrc: './Educationimages/smartphone.jpg',
    name: " Smart phone cover    ",
    details: "Constructed from high-quality materials, the Smartphone Protection Case offers reliable protection against drops, impacts, and everyday wear and tear. Its precise fit and reinforced corners provide added defense for your device, allowing you to focus on your educational activities without worrying about accidental damage.        ",
    price: " Price:$15",
},
{
    id: 129,
    imgSrc: './eyewearimages/offswhitefashionframesluxxury.jpg',
    name: " Offs white fashion frames luxury sunglasses ",
    details: "   Introducing Off-White Luxury Fashion Sunglasses—an embodiment of style, sophistication, and luxury for your discerning taste. Crafted with exquisite design, premium materials, and attention to detail, our sunglasses offer a unique fusion of fashion and function, allowing you to make a bold statement during your travels and beyond.        ",
    price: " Price:$50",
},
{
    id: 130,
    imgSrc: './eyewearimages/fashinvintagesmallframesunglasses.jpg',
    name: " Fashin vintlage small frame sunglasses    ",
    details: "Constructed with small frame dimensions and high-quality materials, Fashion Vintage Small Frame Sunglasses bring back the elegance of bygone eras while offering UV protection. The vintage-inspired design complements your individuality and complements a variety of outfits, making them a versatile accessory.",
    price: " Price:$50",
},
{
    id: 131,
    imgSrc: './eyewearimages/fashionsmallframesumglasses.jpg ',
    name: "  Fashion small frame sunglasses    ",
    details: "    Whether you're exploring bustling city streets, soaking in scenic landscapes, or attending cultural events, our small frame sunglasses become your fashion-forward companion. They add an element of modern allure to your look while shielding your eyes from the sun.",
    price: " Price:$50",
},
{
    id: 132,
    imgSrc: './eyewearimages/genericrectanglesunglasess.jpg',
    name: " Generic rectangle sunglasses    ",
    details: " Equipped with a comfortable fit, durable construction, and a design that transcends trends, Classic Rectangle Sunglasses are designed to stand the test of time. They reflect your appreciation for enduring style and your commitment to a polished appearance.        ",
    price: " Price:$35",
},
{
    id: 133,
    imgSrc: './eyewearimages/italianmadesunglasses.jpg',
    name: "Italian made sunglasses    ",
    details: "   Elevate your travel experience with Italian Crafted Sunglasses—an accessory that seamlessly blends art and fashion. From immersing yourself in the beauty of Italian cities to capturing unforgettable moments with sophistication, these sunglasses are your ultimate companion, allowing you to fully embrace the excitement and allure of your journey.        ",
    price: " Price:$70",
},
{
    id: 134,
    imgSrc: './eyewearimages/trendysquaresunglsses.webp',
    name: "Trendy square sunglasses    ",
    details: "    Introducing Trendsetting Square Sunglasses—a modern and stylish accessory designed to set new fashion standards with a contemporary twist. Crafted with bold lines, edgy aesthetics, and on-trend appeal, these sunglasses offer a fresh and dynamic look that captures the essence of current fashion trends during your travels.        ",
    price: " Price:$70",
},
{
    id: 135,
    imgSrc: './eyewearimages/womenirregular.webp',
    name: "Women irregular sunglasses    ",
    details: "   Equipped with a comfortable fit, meticulous craftsmanship, and a design that stands out, Chic Irregular Sunglasses for Women are crafted to capture attention. They reflect your willingness to embrace unconventional beauty and express your unique style.        ",
    price: " Price:$35",
},
{
    id: 136,
    imgSrc: './eyewearimages/3.jpg',
    name: " Essential by eleventh:hour    ",
    details: "  Whether you're catching a flight, exploring a new city, or engaging in educational activities, Eleventh:Hour Essentials become your reliable companions. They add an extra layer of convenience to your travel experience, allowing you to focus on making memories and embracing new adventures.        ",
    price: " Price:$35",
},
{
    id: 137,
    imgSrc: './eyewearimages/PTQsunglassesforman.jpg',
    name: "PTQ sunglasses for man    ",
    details: "Introducing Premium PTQ Sunglasses for Men—an embodiment of style, quality, and modern sophistication. Crafted with precision, top-notch materials, and attention to detail, these sunglasses offer a premium and refined accessory that complements the modern man's sense of fashion during his travels and daily life.        ",
    price: " Price:$35",
},

// eye wear picture end
// travel health picture start
{
    id: 138,
    imgSrc: './Travel_healthimages/acustraps.png',
    name: "Acustraps",
    details: " Introducing Acustraps—an innovative and comfortable solution designed to enhance your travel experience by addressing motion sickness and discomfort. Crafted with advanced technology and a focus on your well-being, Acustraps offer relief from the challenges of motion-related discomfort, allowing you to fully enjoy your journeys without worry.        ",
    price: " Price:$07",
},
{
    id: 139,
    imgSrc: './Travel_healthimages/bug_guard.png',
    name: "Bug guards",
    details: "Constructed with high-quality materials and effective bug-repelling mechanisms, Bug Guards provide a layer of defense against mosquitoes and other pests. The innovative design ensures you can explore outdoor environments without the annoyance of insect bites.        ",
    price: " Price:$08",
},
{
    id: 140,
    imgSrc: './Travel_healthimages/moqui.png',
    name: "Mosqui-Go electric",
    details: "Whether you're staying in accommodations, camping in the wilderness, or simply relaxing on your balcony, Mosqui-Go Electric becomes your insect-free haven. It ensures you can fully embrace your surroundings and engage in activities without worrying about insect intrusions.        ",
    price: " Price:$05",
},
{
    id: 141,
    imgSrc: './Travel_healthimages/relif.png',
    name: "Mosqui-Go refills",
    details: "Elevate your travel experience with Mosqui-Go Refills—an accessory that seamlessly combines effectiveness and practicality. From peaceful nights to uninterrupted outdoor activities, Mosqui-Go Refills are your trusted partners, allowing you to fully embrace the excitement and comfort of your journey.        ",
    price: " Price:$07",
},
{
    id: 142,
    imgSrc: './Travel_healthimages/socks.png',
    name: "Flight socks",
    details: "Introducing Flight Comfort Socks—an essential accessory designed to enhance your travel experience by prioritizing your comfort and well-being during flights. Crafted with premium materials and innovative design, Flight Comfort Socks offer support and relief to your legs, ensuring you arrive at your destination feeling refreshed and revitalized.        ",
    price: " Price:$05",
},
{
    id: 143,
    imgSrc: './images/beachfirstaid.avif',
    name: "First-aid kit",
    details: " Whether you're exploring remote areas, participating in outdoor activities, or simply navigating new environments, the Comprehensive First Aid Kit becomes your safety companion. It offers a quick response to minor medical issues, allowing you to continue enjoying your travels without worry.        ",
    price: " Price:$10",
},


// travel health picture end
// clothes/laundary picture start
{
    id: 144,
    imgSrc: './clothesimages/laundrybag.png',
    name: "Laundry bag",
    details: " Introducing the Travel Laundry Bag—an essential accessory designed to help you stay organized and keep your clothes fresh while you're on the go. Crafted with durable materials and a user-friendly design, this laundry bag offers a convenient solution for managing your laundry during your travels. ",
    price: " Price:$25",
},
{
    id: 145,
    imgSrc: './clothesimages/thesuiter.png',
    name: "The suiter",
    details: " Constructed with high-quality materials and specialized compartments, The Suiter provides a dedicated space to store your formal wear. The innovative design minimizes creases and wrinkles, allowing you to arrive at your destination with your clothing looking as impeccable as when you packed it.        ",
    price: " Price:$15",
},
{
    id: 146,
    imgSrc: './clothesimages/travelclothesline.png',
    name: "Travel clothes line",
    details: " Whether you're exploring new places, participating in outdoor activities, or simply moving between accommodations, the Portable Travel Clothes Line becomes your reliable companion. It ensures your clothes are dry and ready for wear, regardless of the circumstances. ",
    price: " Price:$17",
},
{
    id: 147,
    imgSrc: './clothesimages/triplespackingcubes.png',
    name: " Travel packing cubes",
    details: " Whether you're embarking on a short getaway, a lengthy vacation, or a business trip, Travel Packing Cubes become your packing companions. They ensure that your clothes remain wrinkle-free, accessories stay organized, and your travel essentials are easily accessible.   ",
    price: " Price:$35",
},
{
    id: 148,
    imgSrc: './clothesimages/twinpackingcubes.png',
    name: "Twin packing cubes",
    details: "Elevate your travel experience with Twin Packing Cubes—an accessory that seamlessly combines organization and efficiency. From new explorations to capturing memories, Twin Packing Cubes are your trusted partners, allowing you to fully embrace the excitement and orderliness of your journey.        ",
    price: " Price:$45",
},
{
    id: 149,
    imgSrc: './clothesimages/wetordrybag.png',
    name: "Wet or dry bag",
    details: " Introducing the Wet and Dry Bag—a versatile and practical accessory designed to accommodate both wet and dry items during your travels. Crafted with waterproof materials and thoughtful design, this bag offers a convenient solution for keeping your belongings organized and protecting them from moisture.     ",
    price: " Price:$24",
},
// clothes/laundary picture end

// power picture start
{
    id: 150,
    imgSrc: './powerimage/incartwinusb.jpg',
    name: "In car twin USB",
    details: " Introducing the In-Car Twin USB Charger—an essential accessory designed to keep your devices powered while you're on the road. Crafted with convenience and efficiency in mind, this charger offers a reliable source of power for multiple devices, ensuring you stay connected and charged during your travels.        ",
    price: " Price:$50",
},
{
    id: 151,
    imgSrc: './powerimage/incarusbcharger.jpg',
    name: "In car USB charger",
    details: " Constructed with a compact and user-friendly design, the In-Car USB Charger plugs into your vehicle's cigarette lighter or power outlet. Equipped with USB ports, it allows you to charge your devices such as smartphones, tablets, and more, without the need for additional adapters.        ",
    price: " Price:$50",
},
{
    id: 152,
    imgSrc: './powerimage/uk-ueadaptor.png',
    name: "UK-UE adaptor",
    details: "   Whether you're exploring vibrant cities, historical landmarks, or scenic landscapes across the European continent, the UK to EU Adaptor becomes your power solution. It ensures that your devices remain connected and functional, enhancing your travel experience.        ",
    price: " Price:$50",
},
{
    id: 153,
    imgSrc: './powerimage/3in1retracable.jpg',
    name: "3 in 1 retracable connertor cable (M)",
    details: " Introducing the 3-in-1 Retractable Connector Cable (M)—a versatile and space-saving accessory designed to simplify your charging and data transfer needs. Crafted with convenience and functionality in mind, this cable offers a compact solution for connecting multiple        ",
    price: " Price:$35",
},
{
    id: 154,
    imgSrc: './powerimage/usbcharger.png',
    name: "USB charger",
    details: " Equipped with fast-charging capabilities, compact design, and compatibility with various devices, the USB Charger enhances your convenience and versatility. It reflects our commitment to providing you with a solution that keeps you powered up no matter where you are.        ",
    price: " Price:$70",
},
{
    id: 155,
    imgSrc: './powerimage/usbin-carcharger.png',
    name: "USB in-car charger",
    details: "   Whether you're navigating through unfamiliar routes, enjoying your favorite music, or making important calls, the In-Car USB Charger becomes your essential travel companion. It ensures that your devices remain charged and operational, enhancing your travel experience.        ",
    price: " Price:$70",
},
{
    id: 156,
    imgSrc: './powerimage/usb-cconector.jpg',
    name: "USB-C connector",
    details: "  A USB-C connector, also known as USB Type-C, is a versatile and widely used connector standard for transferring data and power between devices. It was introduced as a successor to various older USB standards and has gained popularity due to its compact design, reversible plug orientation, and support for high-speed data transfer and charging capabilities. Here are some key features and information about USB-C connectors:        ",
    price: " Price:$35",
},
{
    id: 157,
    imgSrc: './powerimage/worldwideadaptor.png',
    name: "World wide adaptor",
    details: "  A worldwide adapter, often referred to as a travel adapter or universal adapter, is an essential accessory for travelers to ensure that their electronic devices can be plugged into different types of electrical outlets around the world. Electrical outlets and voltage standards vary from country to country, which can create compatibility issues for travelers using devices with different types of plugs.        ",
    price: " Price:$35",
},
{
    id: 158,
    imgSrc: './powerimage/worlswide3portusb.jpg',
    name: "world wide 3 port USB",
    details: "   A worldwide 3-port USB charger is a versatile device that allows you to charge multiple electronic devices simultaneously using a single charger, and it's designed to be compatible with different types of electrical outlets found around the world.  ",
    price: " Price:$35",
},
// power picture end
// water bottle picture start
{
    id: 159,
    imgSrc: './bottle_image/grandTieswaterbottle.jpg',
    name: "Grandties water bottle",
    details: " Introducing the GrandTies Water Bottle—an essential companion for staying hydrated during your adventures. Crafted with style and functionality in mind, this water bottle offers a convenient and eco-friendly way to quench your thirst while on the go.        ",
    price: " Price:$35",
},
{
    id: 160,
    imgSrc: './bottle_image/plasticwaterbottle.jpg',
    name: "Plastic water bottle",
    details: "Constructed with durable and BPA-free plastic, the Reusable Plastic Water Bottle ensures that you have a reliable and safe vessel for carrying your drinks. Its reusable nature makes it a responsible choice, reducing the need for disposable plastic bottles that harm our planet.        ",
    price: " Price:$22",
},
{
    id: 161,
    imgSrc: './bottle_image/resuablewaterbottle.jpg',
    name: "Resuable water bottle",
    details: "Constructed with durable and eco-conscious materials, the Reusable Water Bottle ensures that you have a reliable and safe container for your beverages. Its reusable design reduces the need for single-use plastic bottles, making a positive impact on the environment.        ",
    price: " Price:$33",
},
{
    id: 162,
    imgSrc: './bottle_image/stainlesssteelwater.jpg',
    name: "Stainless steel water bottle",
    details: "Elevate your daily routine with the Stainless Steel Water Bottle—an accessory that seamlessly combines durability and elegance. From busy days to leisurely moments, the Stainless Steel Water Bottle is your dependable partner, allowing you to fully embrace the refreshment and sophistication of your hydration.        ",
    price: " Price:$35",
},
{
    id: 163,
    imgSrc: './bottle_image/thebestwaterbottel.jpg',
    name: "Best water bottle",
    details: " Whether you're on a hiking trail, at the gym, or at your desk, the Ultimate Water Bottle becomes your go-to companion. Its innovative features, leak-proof design, and durability make it a reliable choice for all your hydration needs.        ",
    price: " Price:$47",
},
{
    id: 164,
    imgSrc: './bottle_image/theleakproofwater.jpg',
    name: "Leackproof water bottle",
    details: "Introducing the Leakproof Water Bottle—an essential accessory that ensures you stay hydrated without the worry of spills and leaks. Crafted with precision and convenience in mind, this water bottle offers a reliable solution for quenching your thirst on the go.        ",
    price: " Price:$70",
},
{
    id: 165,
    imgSrc: './bottle_image/thermalsealwater.jpg',
    name: "Thermal seal water bottle    ",
    details: "Introducing the Thermal Seal Water Bottle—a premium accessory designed to elevate your hydration experience while maintaining the perfect drink temperature. Crafted with sophistication and innovation in mind, this water bottle offers a blend of style, functionality, and temperature preservation.        ",
    price: " Price:$35",
},
{
    id: 166,
    imgSrc: './bottle_image/travelbottle1.jpg',
    name: "Travel water bottle",
    details: "Constructed with lightweight and durable materials, the Travel Water Bottle is designed to accompany you on all your adventures. Its compact size fits seamlessly into backpacks, bags, and cup holders, making it the perfect companion for travel, commuting, and outdoor activities.        ",
    price: " Price:$35",
},
{
    id: 167,
    imgSrc: './bottle_image/waterbottle.png',
    name: "Water bottle",
    details: " Elevate your daily routine with the Water Bottle—an accessory that seamlessly combines functionality and simplicity. From busy schedules to moments of relaxation, the Water Bottle is your trusted partner, allowing you to fully embrace the refreshment and vitality of every sip.        ",
    price: " Price:$35",
},

// water bottle picture end
// sleep well picture start

{
    id: 168,
    imgSrc: './sleepwellimages/classicblanket.jpg',
    name: "Classic blanket    ",
    details: "Introducing the Classic Blanket—an iconic accessory designed to provide you with timeless comfort and warmth. Crafted with quality materials and enduring style in mind, this blanket offers a versatile solution for cozy moments and relaxation.        ",
    price: " Price:$50",
},
{
    id: 169,
    imgSrc: './sleepwellimages/customfitearplugs.png',
    name: "Custom fit ear plugs",
    details: "Introducing the Classic Blanket—an iconic accessory designed to provide you with timeless comfort and warmth. Crafted with quality materials and enduring style in mind, this blanket offers a versatile solution for cozy moments and relaxation.        ",
    price: " Price:$33",
},
{
    id: 170,
    imgSrc: './sleepwellimages/shapedeyemask.png',
    name: "Shaped eye mask",
    details: " Constructed with soft and gentle materials, the Shaped Eye Mask contours to the shape of your face, ensuring a comfortable fit that doesn't put pressure on your eyes. Its innovative design blocks out unwanted light, creating a serene environment for you to unwind and recharge.        ",
    price: " Price:$20",
},
{
    id: 171,
    imgSrc: './sleepwellimages/silkyeyemask.png',
    name: "Silky eye mask",
    details: "Introducing the Silky Eye Mask—an indulgent accessory designed to envelop you in luxurious comfort for a serene sleep experience. Crafted with the finest materials and a touch of elegance, this eye mask offers a soothing solution for blocking out light and enhancing your relaxation.        ",
    price: " Price:$24",
},
{
    id: 172,
    imgSrc: './sleepwellimages/supersleepeyemask.png',
    name: "Super sleep eye mask",
    details: "Whether you're a frequent traveler, a light sleeper, or simply seeking to optimize your rest, the Super Sleep Eye Mask becomes your secret weapon. It creates an environment of complete darkness, shielding your eyes from light pollution and distractions.        ",
    price: " Price:$34",
},
{
    id: 173,
    imgSrc: './sleepwellimages/supersoftearplugfs.png',
    name: "Super soft ear plugs",
    details: " Constructed with a unique blend of plush materials, the Super Soft Ear Plugs mold to the contours of your ears, ensuring a snug and comfortable fit. Their exceptional softness makes them perfect for extended wear, allowing you to enjoy peace and quiet without any discomfort.        ",
    price: " Price:$45",
},
{
    id: 174,
    imgSrc: './sleepwellimages/thedreamereyemask.jpg',
    name: "The dreamer eye mask",
    details: " Elevate your sleep experience with The Dreamer Eye Mask—an accessory that seamlessly blends comfort and wonder. From serene nights to dreams yet to be discovered, The Dreamer Eye Mask is your imaginative partner, allowing you to fully embrace the enchantment and tranquility of each slumber.",
    price: " Price:$35",
},
{
    id: 175,
    imgSrc: './sleepwellimages/ultimate2.0.png',
    name: "Ultimate 2.0 Pillow",
    details: "Introducing the Ultimate 2.0 Pillow—an advanced sleep accessory designed to redefine your sleep experience and transform your nights into rejuvenating rest. Crafted with cutting-edge technology and unparalleled comfort in mind, this pillow offers a superior solution for achieving optimal sleep quality.        ",
    price: " Price:$35",
},
{
    id: 176,
    imgSrc: './sleepwellimages/memorydreamer.png',
    name: "Memory dreamer",
    details: "Constructed with plush memory foam and gentle materials, the Memory Dreamer cradles your head and neck, ensuring a cozy and supportive fit. Its adaptive design aligns your spine, allowing you to rest without the discomfort of improper sleep posture.        ",
    price: " Price:$35",
},

//  sleep well picture end
//  advantrous tour picture start
{
    id: 177,
    imgSrc: './advantoursimgs/gpsmap.jpg',
    name: "GPS Map",
    details: "Constructed with comprehensive trail data, topographic information, and real-time updates, the GPS Map for Adventurous Tours ensures that you can embark on your journeys with a clear understanding of your surroundings. Its user-friendly interface provides crucial details such as elevation, landmarks, and trail difficulty, enabling you to plan and execute your adventures effectively.        ",
    price: " Price:$50",
},
{
    id: 178,
    imgSrc: './advantoursimgs/proteinbar.jpg',
    name: "Protein Bar",
    details: " Constructed with high-quality protein, essential carbohydrates, and vitamins, the Protein Bar for Adventurous Tours ensures that you have the sustenance you need to power through your activities. Its compact and portable design makes it easy to carry in your backpack, ensuring you're always ready for the next leg of your journey.        ",
    price: " Price:$10",
},
{
    id: 179,
    imgSrc: './advantoursimgs/tant.jpg',
    name: "Tent",
    details: " Introducing the Adventure-Ready Tent—an essential companion designed to provide you with shelter, comfort, and protection during your adventurous tours. Crafted with durability and convenience in mind, this tent offers a reliable solution for creating a home away from home in the great outdoors.        ",
    price: " Price:$35",
},
{
    id: 180,
    imgSrc: './advantoursimgs/firstaid.jpg',
    name: "Mini First Aid",
    details: " Constructed with essential medical supplies and a compact design, the Mini First Aid Kit ensures that you're equipped to handle unexpected situations during your outdoor adventures. Its lightweight and portable nature allows you to carry it in your backpack, ensuring you're always prepared for the unexpected.        ",
    price: " Price:$20",
},
{
    id: 181,
    imgSrc: './advantoursimgs/bottle.jpg',
    name: "Bottle",
    details: "Introducing the versatile Bottle—an essential container designed to cater to a wide range of needs, from keeping you hydrated to storing liquids and more. Crafted with convenience and functionality in mind, this container offers a practical solution for carrying liquids on the go. ",
    price: " Price:$15",
},
{
    id: 182,
    imgSrc: './advantoursimgs/flashligth.jpg',
    name: "Flash Light",
    details: " Whether you're hiking through dense forests, setting up camp after sunset, or exploring caves, the Adventure-Ready Flashlight becomes your guiding light. It helps you uncover hidden details, stay safe, and enjoy every aspect of your outdoor journey.        ",
    price: " Price:$15",
},
{
    id: 183,
    imgSrc: './advantoursimgs/hikingbag.jpg',
    name: "Hiking Bag",
    details: "Elevate your outdoor journey with the Adventurous Tour Hiking Backpack—an accessory that seamlessly combines durability and adventure. From multi-day treks to day hikes, the Adventurous Tour Hiking Backpack is your essential partner, allowing you to fully embrace the excitement and challenges of your adventurous tours.        ",
    price: " Price:$55",
},
{
    id: 184,
    imgSrc: './advantoursimgs/hikingshoes.jpg',
    name: "Hiking Shoes",
    details: " Introducing the Adventurous Tour Hiking Shoes—a vital component of your outdoor gear designed to help you conquer every terrain and trail. Crafted with durability, support, and traction in mind, these hiking shoes offer a reliable solution for navigating rugged landscapes and embracing the challenges of adventurous tours.        ",
    price: " Price:$80",
},
{
    id: 185,
    imgSrc: './advantoursimgs/jacket.webp',
    name: "Jacket",
    details: " Constructed with weather-resistant materials and functional design, the Adventure-Ready Jacket is built to withstand wind, rain, and other outdoor challenges. Its breathable yet insulated features ensure you stay comfortable whether you're trekking through forests, scaling peaks, or simply enjoying the wilderness.        ",
    price: " Price:$60",
},
{
    id: 186,
    imgSrc: './advantoursimgs/pocketknife.jpg',
    name: "Pocket Knife",
    details: " Introducing the Pocket Knife—an essential tool designed to be your compact outdoor companion for a wide range of tasks and situations. Crafted with versatility and portability in mind, this knife offers a reliable solution for various cutting, slicing, and utility needs during your outdoor adventures        ",
    price: " Price:$30",
},
{
    id: 187,
    imgSrc: './advantoursimgs/toolbelt.jpg',
    name: "Tool Belt",
    details: " Constructed with sturdy materials and a user-friendly design, the Adventure-Ready Tool Belt is built to withstand the demands of various tasks and activities. Its adjustable straps ensure a secure and comfortable fit, allowing you to move freely while having your tools within reach.        ",
    price: " Price:$40",
},
{
    id: 188,
    imgSrc: './advantoursimgs/towel.webp',
    name: "Towel",
    details: " Equipped with a convenient carry pouch, antimicrobial properties, and a commitment to enhancing your outdoor experience, the  Towel elevates your comfort level. It reflects our dedication to providing you with a versatile accessory that supports your need for hygiene and convenience in the wild. ",
    price: " Price:$10",
},
//  advantrous tour picture end
//  first -aid picture start
{
    id: 189,
    imgSrc: './firstaidimages/antisepticsolutionstock.jpg',
    name: "Antiseptic solution stock",
    details: "  Introducing Antiseptic Solution—an essential item for your first aid kit, designed to provide immediate care and prevent infection for minor cuts, scrapes, and wounds. Crafted with germ-fighting properties, this solution offers a reliable solution for maintaining hygiene and promoting healing in emergency situations.",
    price: " Price:$15",
},
{
    id: 190,
    imgSrc: './firstaidimages/bandAid.jpg',
    name: "Band Aid",
    details: "Introducing the Band-Aid—an iconic and essential item for your first aid kit, designed to provide quick and effective wound care wherever you are. Crafted with comfort and convenience in mind, the Band-Aid offers a reliable solution for protecting and promoting healing for minor cuts, grazes, and abrasions. ",
    price: " Price:$10",
},
{
    id: 191,
    imgSrc: './firstaidimages/elasticbandagestock.jpg',
    name: "Elastic bandage stock",
    details: " Constructed with elasticity and comfort in mind, the Elastic Bandage conforms to the shape of the body and provides gentle compression to minimize swelling and promote healing. Its flexibility and adjustability make it a valuable asset for sprains, strains, and other soft tissue injuries.        ",
    price: " Price:$08",
},

{
    id: 192,
    imgSrc: './firstaidimages/medicaltape.jpg',
    name: "Medical tape",
    details: " Whether you're applying dressings to cuts, protecting blisters, or securing gauze pads, Medical Tape becomes your reliable aid. It supports your wound care regimen and enables you to maintain hygiene and protection for injured areas.        ",
    price: " Price:$15",
},
{
    id: 193,
    imgSrc: './firstaidimages/medicaltweeezers.jpg',
    name: "Medical tweezer",
    details: "Elevate your wound care regimen with Medical Tweezers—an essential component that ensures your ability to remove foreign objects safely and effectively. From splinters to minor injuries, Medical Tweezers are your precise partner, allowing you to fully address and alleviate discomfort with confidence.        ",
    price: " Price:$55",
},
{
    id: 194,
    imgSrc: './firstaidimages/surgicalguaze.jpg',
    name: "Surgical guaze",
    details: "  Constructed with high-quality, sterile materials, surgical gauze is designed to absorb moisture and facilitate the healing process. Its soft and gentle texture ensures minimal discomfort while providing a protective barrier against contaminants. ",
    price: " Price:$15",
},
{
    id: 195,
    imgSrc: './firstaidimages/afebff96e0c14a8b46f4cfe2bc2bd845.png',
    name: "Penadol medicine",
    details: " Introducing Panadol—an established and reliable over-the-counter pain relief medicine designed to provide comfort and alleviate aches. Crafted with efficacy and safety in mind, Panadol offers a trusted solution for managing various types of pain and discomfort.        ",
    price: " Price:$10",
},

// first -aid  picture end
//sunblock  picture start
{
    id: 196,
    imgSrc: './sunblockimages/10bestmenssunscreen.jpg',
    name: "LA ROCHE-POSAY sunscreen",
    details: " Introducing Oriflame Men's Sunblock—a specialized skincare product designed to provide effective protection against the sun's harmful UV rays. Crafted with advanced formula and skin-friendly ingredients, this sunblock offers a reliable solution for maintaining healthy and protected skin.        ",
    price: " Price:$15",
},
{
    id: 197,
    imgSrc: './sunblockimages/GLORIL-SUNBLOCK-30GM.jpg',
    name: "Multi Grain SUNBLOCK-30GM",
    details: "Introducing Multi-Grain Sunblock—an innovative skincare product designed to provide effective sun protection while nourishing your skin. Crafted with a blend of beneficial ingredients, this sunblock offers a reliable solution for shielding your skin from harmful UV rays while promoting its health.        ",
    price: " Price:$10",
},
{
    id: 198,
    imgSrc: './sunblockimages/kidscreambodyproduct.jpg',
    name: "Kid's cream body product",
    details: "Introducing Kids' Creamy Body Delight—a specially formulated body care product designed to provide gentle and nurturing care for your child's delicate skin. Crafted with love and skin-friendly ingredients, this cream offers a reliable solution for keeping your child's skin soft, moisturized, and happy.        ",
    price: " Price:$08",
},
{
    id: 199,
    imgSrc: './sunblockimages/kidsskincareproducts.jpg',
    name: "Mama and Kids sunblock",
    details: " Introducing Mama and Kids Sunblock—an all-inclusive sun protection solution designed for both mothers and children. Crafted with a gentle formula and advanced UV-blocking agents, this sunblock offers a reliable solution for keeping the whole family's skin safe from harmful rays. ",
    price: " Price:$15",
},
{
    id: 200,
    imgSrc: './sunblockimages/mensskincarecream.jpg',
    name: "ORIFLAME man's sunblock",
    details: "Introducing Oriflame Men's Sunblock—an essential skincare product designed specifically for men to provide effective protection against the sun's harmful UV rays. Crafted with advanced formula and skin-friendly ingredients, this sunblock offers a reliable solution for maintaining healthy and well-protected skin.        ",
    price: " Price:$25",
},
{
    id: 201,
    imgSrc: './sunblockimages/sunblock-1-1080x710.png',
    name: " vince Sunblock",
    details: "Formulated with broad-spectrum UV filters, Vince Sunblock safeguards your skin from both UVA and UVB rays, helping to prevent sunburn, premature aging, and potential skin damage. Its lightweight and non-greasy texture ensures easy application and absorption without leaving any residue.        ",
    price: " Price:$15",
},
// sunblock picture end
// cold placse picture start
{
    id: 202,
    imgSrc: './coldplacesimg/jacket.jpg',
    name: " Leather Jacket",
    details: "   Introducing the Leather Jacket—a timeless and iconic wardrobe piece that combines style, comfort, and durability. Crafted with genuine leather and meticulous attention to detail, this jacket offers a versatile solution for enhancing your fashion statement while keeping you warm and protected.        ",
    price: " Price:$50",
},
{
    id: 203,
    imgSrc: './coldplacesimg/shoes.webp',
    name: " Warm Shoes",
    details: " Introducing Warm Shoes—a footwear solution designed to provide you with snug and cozy comfort during chilly weather. Crafted with insulating materials and thoughtful design, these shoes offer a reliable way to keep your feet warm while maintaining your style.        ",
    price: " Price:$40",
},
{
    id: 204,
    imgSrc: './coldplacesimg/earflaps.jpg',
    name: "Ear Flaps ",
    details: "  Designed with soft and insulating materials, ear flaps cover your ears and help trap heat, preventing discomfort from chilly winds. Their practical construction ensures that you can stay warm and cozy without compromising on style. ",
    price: " Price:$25",
},
{
    id: 205,
    imgSrc: './coldplacesimg/firstaidkit.jpg',
    name: "Mini First-Aid ",
    details: " Whether you're hiking, traveling, or simply going about your day, the Mini First Aid Kit becomes your go-to resource. It offers quick and efficient solutions for cuts, scrapes, and minor injuries, allowing you to address them promptly and with confidence.        ",
    price: " Price:$20",
},
{
    id: 206,
    imgSrc: './coldplacesimg/scarf.jpg',
    name: " Scarf",
    details: "  Introducing the Scarf—an iconic accessory that effortlessly combines warmth and style to enhance your ensemble. Crafted with a variety of materials, colors, and patterns, the scarf offers a versatile way to stay cozy while adding a touch of elegance to your look.        ",
    price: " Price:$15",
},
{
    id: 207,
    imgSrc: './coldplacesimg/stick.jpg',
    name: "Hiking Stick ",
    details: " Introducing the Hiking Stick—an indispensable companion for your cold weather adventures in the great outdoors. Crafted for durability and functionality, this essential tool provides support, stability, and added confidence as you navigate through challenging terrains and frosty landscapes.        ",
    price: " Price:$09",
},
{
    id: 208,
    imgSrc: './coldplacesimg/socks.jpg',
    name: "Socks ",
    details: " Introducing Cold-Weather Socks—an essential accessory designed to provide you with superior warmth and comfort during your chilly escapades. Crafted with insulating materials and thoughtful design, these socks offer a reliable way to keep your feet cozy and protected in cold climates.        ",
    price: " Price:$11",
},
{
    id: 209,
    imgSrc: './coldplacesimg/waterproofgloves.jpg',
    name: "Water Proof Gloves ",
    details: "Designed with waterproof and breathable membranes, Waterproof Gloves ensure that your hands stay shielded from rain, snow, and moisture. Their durable construction and sealed seams prevent water from seeping in, allowing you to enjoy your outdoor adventures without worrying about wet hands.        ",
    price: " Price:$20",
},
{
    id: 2010,
    imgSrc: './coldplacesimg/winterhat.jpg',
    name: " Winter Hat",
    details: "  Whether you're braving the cold winds, enjoying winter activities, or simply stepping out on chilly days, the Winter Hat becomes your go-to accessory. It offers a layer of protection that allows you to stay comfortable and fashionable while facing the elements.  ",
    price: " Price:$05",
},

    // cold placse picture end
]


getTrainerData();

function getTrainerData() {

    let id = getId();

    if (id == null) {
        id = 1;
    }

    trainerData.map((item) => {
        if (item.id == id) {
            document.getElementById('productImg').src = item.imgSrc;
            document.getElementById('name').innerText = item.name;
            document.getElementById('details').innerText = item.details;
            document.getElementById('price').innerText = item.price;

            // document.getElementById('trainerImg').src = item.imgSrc;
            // document.getElementById('specialties-container').innerText = item.specialize;
        }
    })

}